### ISSUE TITLE
Jira UUID field is deprecated

### ISSUE THREAD

**Issue by jorkzijlstra** [Kaliber/play-jira-exception-processor#11]
The UUID field is deprecated in Jira. You can only create Text fields by default which doesn't support the '=' operator.

Jira return the message The operator '=' is not supported by the 'Hash' field

**Comment by jorkzijlstra** [comment]
The contains '~' operator might be the solution, it still support an exact match.
We need to check if this also works on the UUID field for backward compatibility.

https://confluence.atlassian.com/jirasoftwarecloud/advanced-searching-operators-reference-764478341.html#Advancedsearching-operatorsreference-CONTAINS

**Comment by jorkzijlstra** [comment]
Since ~ doens't work on UUID fields a configuration option is now available to choose between UUID and text.

**Comment by EECOLOR** [comment]
Closing in favor of #13
